CREATE TABLE schemas.bronze.metacritic_toppc_games (
  Name STRING COMMENT 'The title of the game or application, which is used to identify it in the dataset.',
  Release_Date STRING COMMENT 'The date when the game or application was officially released to the public.',
  Rating STRING COMMENT 'The overall rating given to the game or application, reflecting user satisfaction.',
  Description STRING COMMENT 'A brief summary or overview of the game or application, highlighting its main features and gameplay.',
  Score STRING COMMENT 'A numerical representation of the game\'s quality, often derived from user reviews and ratings.',
  appid BIGINT COMMENT 'A unique identifier assigned to each game or application within the platform.',
  developer STRING COMMENT 'The name of the company or individual responsible for creating the game or application.',
  publisher STRING COMMENT 'The name of the company that published the game or application, which may differ from the developer.',
  score_rank BIGINT COMMENT 'A ranking based on the score, indicating the relative quality of the game compared to others.',
  positive STRING COMMENT 'The number of positive reviews or feedback received for the game or application.',
  negative BIGINT COMMENT 'The number of negative reviews or feedback received for the game or application.',
  userscore BIGINT COMMENT 'The total score given by users, reflecting their collective opinion on the game or application.',
  owners STRING COMMENT 'The estimated number of users who own the game or application.',
  average_forever BIGINT COMMENT 'The average playtime of users over the entire period since the game\'s release.',
  average_2weeks BIGINT COMMENT 'The average playtime of users over the last two weeks, indicating recent engagement.',
  median_forever BIGINT COMMENT 'The median playtime of users since the game\'s release, providing a central tendency measure.',
  median_2weeks BIGINT COMMENT 'The median playtime of users over the last two weeks, offering insight into recent user behavior.',
  price BIGINT COMMENT 'The current price of the game or application, typically in the platform\'s default currency.',
  initialprice BIGINT COMMENT 'The original price at which the game or application was launched, before any discounts.',
  discount BIGINT COMMENT 'The amount of discount applied to the current price, indicating any promotional offers.',
  ccu BIGINT COMMENT 'The current number of concurrent users playing the game or application at a given time.',
  owners_range STRING COMMENT 'A range estimate of the number of owners, providing a broader context for ownership statistics.',
  average_playTime_total STRING COMMENT 'The average total playtime across all users, reflecting overall engagement with the game.',
  average_playTime_2weeks BIGINT COMMENT 'The average playtime of users over the last two weeks, indicating recent activity levels.',
  median_playTime_total BIGINT COMMENT 'The median total playtime of users, offering a central measure of engagement over time.',
  median_platyime_2weeks BIGINT COMMENT 'The median playtime of users over the last two weeks, providing insight into recent user engagement.',
  price_USD DOUBLE COMMENT 'The current price of the game or application expressed in US dollars.',
  initialprice_USD DOUBLE COMMENT 'The original price of the game or application in US dollars at the time of release.',
  `discount_%` DOUBLE COMMENT 'The percentage discount applied to the current price, useful for evaluating promotional offers.',
  peak_Current_Players_yesterday BIGINT COMMENT 'The highest number of players online at the same time during the previous day.',
  estimated_owners BIGINT COMMENT 'An estimate of the total number of users who own the game or application, providing insight into its popularity.')
USING delta
COMMENT 'The table contains data related to software applications, specifically focusing on their release details, ratings, and user feedback. It includes information such as the application name, release date, developer, publisher, and various scoring metrics. This data can be used to analyze application performance, compare user ratings, and assess trends in software popularity over time.'
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')
